# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Ethereal
site_url: https://znotfireman.github.io/ethereal

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: etherealdoc-dark
      toggle:
        icon: octicons/sun-24
        title: Switch to light theme
    - media: "(prefers-color-scheme: light)"
      scheme: etherealdoc-light
      toggle:
        icon: octicons/moon-24
        title: Switch to dark theme
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.tabs

extra_css:
  - theme/etherealdoc.css

nav:
  - Home: index.md
  - Docs:
    - docs/index.md
    - Installation: docs/installation.md
    - Referece:
        - Plugin API: docs/reference/plugin-api.md
        - Runtime API: docs/reference/plugin-api.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
