# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Ethereal
site_url: https://znotfireman.github.io/ethereal
repo_name: znotfireman/ethereal
repo_url: https://github.com/znotfireman/ethereal

theme:
    logo: "images/ethereal.png"
    favicon: "images/ethereal.png"
    name: material
    custom_dir: docs/overrides
    font:
        text: Source Sans Pro
        code: Fira Code
    palette:
        - media: "(prefers-color-scheme: dark)"
          scheme: ethereal-dark
          toggle:
              icon: fontawesome/solid/sun
              title: Switch to light theme
        - media: "(prefers-color-scheme: light)"
          scheme: ethereal-light
          toggle:
              icon: fontawesome/solid/moon
              title: Switch to dark theme
    icon:
        previous: fontawesome/solid/angle-left
        next: fontawesome/solid/angle-right
        top: fontawesome/solid/angle-up
        repo: fontawesome/brands/github
        search: fontawesome/solid/magnifying-glass
        admonition:
            note: fontawesome/solid/note-sticky
            abstract: fontawesome/solid/book
            info: fontawesome/solid/circle-info
            tip: fontawesome/solid/bullhorn
            success: fontawesome/solid/check
            question: fontawesome/solid/circle-question
            warning: fontawesome/solid/triangle-exclamation
            failure: fontawesome/solid/bomb
            danger: fontawesome/solid/skull
            bug: fontawesome/solid/robot
            example: fontawesome/solid/flask
            quote: fontawesome/solid/quote-left
    features:
        - navigation.instant
        - navigation.instant.progress
        - navigation.sections
        - navigation.indexes
        - navigation.top
        - navigation.tabs
        - navigation.tabs.sticky

extra_css:
    - theme/admonitions.css
    - theme/article.css
    - theme/banner.css
    - theme/consent.css
    - theme/ethereal.css
    - theme/header.css
    - theme/nav.css
    - theme/search.css

nav:
    - Home: index.md
    - Install: install.md
    - Docs:
          - docs/index.md
          - Packages: docs/packages.md
          - Ethereal For Plugins:
                - docs/ethereal-for-plugins/index.md
                - Your First Tool: docs/ethereal-for-plugins/your-first-tool.md
                - Best Practices: docs/ethereal-for-plugins/best-practices.md
          - Ethereal For Games:
                - docs/ethereal-for-games/index.md
          - Reference:
                - docs/reference/index.md
                - Ethereal for Plugins: docs/reference/ethereal-for-plugins.md
                - Ethereal for Games: docs/reference/ethereal-for-games.md
    - Blog:
          - blog/index.md

markdown_extensions:
    - admonition
    - attr_list
    - md_in_html
    - toc:
          title: On this page
          permalink: true
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
          options:
              custom_icons:
                  - docs/overrides/.icons

plugins:
    - search
    - blog

extra:
    consent:
        title: Cookie consent
        description: >-
            We use cookies to recognize your repeated visits and preferences, as well
            as to measure the effectiveness of our documentation and whether users
            find what they're searching for. With your consent, you're helping us to
            make our documentation better.
