# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Aet
site_url: https://team-fireworks.github.io/aet
repo_name: team-fireworks/aet
repo_url: https://github.com/team-fireworks/aet

theme:
    logo: "images/ethereal.png"
    favicon: "images/ethereal.png"
    name: material
    custom_dir: docs/overrides
    font:
        text: Source Sans Pro
        code: Fira Code
    palette:
        - media: "(prefers-color-scheme: dark)"
          scheme: ethereal-dark
          toggle:
              icon: fontawesome/solid/sun
              title: Switch to light theme
        - media: "(prefers-color-scheme: light)"
          scheme: ethereal-light
          toggle:
              icon: fontawesome/solid/moon
              title: Switch to dark theme
    icon:
        close: fontawesome/solid/xmark
        copy: fontawesome/solid/copy
        previous: fontawesome/solid/angle-left
        next: fontawesome/solid/angle-right
        top: fontawesome/solid/angle-up
        repo: fontawesome/brands/github
        search: fontawesome/solid/magnifying-glass
        share: fontawesome/solid/share
        bars: fontawesome/solid/bars
        admonition:
            note: fontawesome/solid/note-sticky
            abstract: fontawesome/solid/book
            info: fontawesome/solid/circle-info
            tip: fontawesome/solid/bullhorn
            success: fontawesome/solid/check
            question: fontawesome/solid/circle-question
            warning: fontawesome/solid/triangle-exclamation
            failure: fontawesome/solid/bomb
            danger: fontawesome/solid/skull
            bug: fontawesome/solid/robot
            example: fontawesome/solid/flask
            quote: fontawesome/solid/quote-left
    features:
        - navigation.instant
        - navigation.instant.progress
        - navigation.sections
        - navigation.indexes
        - navigation.top
        - navigation.tabs
        - navigation.tabs.sticky
        - announce.dismiss
        - navigation.footer
        - search.suggest
        - search.highlight
        - search.share
        - content.tooltips
        - content.code.copy
        - content.code.annotate
        - content.code.select
        - content.footnote.tooltips

extra_css:
    - theme/admonitions.css
    - theme/banner.css
    - theme/consent.css
    - theme/content.css
    - theme/ethereal.css
    - theme/footer.css
    - theme/header.css
    - theme/nav.css
    - theme/page.css
    - theme/search.css

nav:
    - Home: index.md
    - Installation: installation.md
    - Docs:
          - Tour of Ethereal: docs/tour-of-ethereal.md
          - Packages: docs/packages.md
          - Contributing to Ethereal: docs/contributing-to-ethereal.md
          - "Why Ethereal?": docs/why-ethereal.md
          - Ethereal For Plugins:
                - docs/et-for-plugins/index.md
                - Your First Tool: docs/et-for-plugins/your-first-tool.md
          - Ethereal For Games:
                - docs/et-for-games/index.md
          - API Reference:
                - docs/api-reference/index.md
                - Ethereal for Plugins: docs/api-reference/et-for-plugins.md
                - Ethereal for Games: docs/api-reference/et-for-games.md
    - Blog:
          - blog/index.md
    # - Made with ❤️ by znotfireman: https://github.com/znotfireman

markdown_extensions:
    - admonition
    - attr_list
    - md_in_html
    - toc:
          title: On this page
          permalink: true
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
          options:
              custom_icons:
                  - docs/overrides/.icons

plugins:
    - search
    - blog

extra:
    consent:
        title: Cookie consent
        description: >-
            We use cookies to recognize your repeated visits and preferences, as well
            as to measure the effectiveness of our documentation and whether users
            find what they're searching for. With your consent, you're helping us to
            make our documentation better.
