# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
rojo = "rojo-rbx/rojo@7.4.4"
luau-lsp = "JohnnyMorganz/luau-lsp@1.39.0"
StyLua = "JohnnyMorganz/StyLua@2.0.2"
asphalt = "roblaudio/asphalt@0.8.41"
wally = "UpliftGames/wally@0.3.2"
lune = "lune-org/lune@0.8.9"

# doesnt work on macos yay
# moonwave = "evaera/moonwave@1.2.1"
