name = "znotfireman/ethereal_for_plugins"
version = "0.1.0"
description = "Plugin/Tool APIs for Ethereal, the full-featured Eternal Towers of Hell companion plugin."
authors = ["Fire <znotfireman@gmail.com>"]
repository = "https://github.com/znotfireman/ethereal"
license = "GPL-3.0-only"
includes = ["pesde.toml", "README.md", "LICENSE.md", "init.luau"]

[target]
environment = "roblox"
lib = "init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }
