return {
	icons = {
		caretUp = "rbxasset://.asphalt-ethanol/icons/caretUp.288138de306bbdc9edbe2689b6fc1400.png",
		gear = "rbxasset://.asphalt-ethanol/icons/gear.df41f13312bf357c1034eb1b228efd67.png",
		image = "rbxasset://.asphalt-ethanol/icons/image.1a43a6a21c8d4c66ffde2d2df9e0eb76.png",
		rocket = "rbxasset://.asphalt-ethanol/icons/rocket.34f377a5e0efc33716a54235fccf7d3c.png",
		soundFull = "rbxasset://.asphalt-ethanol/icons/soundFull.86f522930947c21900c2711939cb8621.png",
		swatchbook = "rbxasset://.asphalt-ethanol/icons/swatchbook.65a3415f65933ce93f4ed4a3b4593b04.png",
		toolbox = "rbxasset://.asphalt-ethanol/icons/toolbox.02be4f2c9e084644825fa4a05c436d67.png",
		wandMagicSparkles = "rbxasset://.asphalt-ethanol/icons/wandMagicSparkles.472708c41240058022720c48ee331aae.png",
		wrench = "rbxasset://.asphalt-ethanol/icons/wrench.cd53f5e00f758a987d571b57072b662b.png",
	},
	images = {
		ethereal = "rbxasset://.asphalt-ethanol/images/ethereal.3cb8e1c6fad58dc313761843b4239857.png",
		etoh = "rbxasset://.asphalt-ethanol/images/etoh.93735367d28759da424dbc2723cb0026.png",
	},
	sfx = {
		click = "rbxasset://.asphalt-ethanol/sfx/click.da815722c4e9550204156ceb371073cc.ogg",
		hover = "rbxasset://.asphalt-ethanol/sfx/hover.8f3a3893ee67c30f0f324f60fae23e39.ogg",
		softClick = "rbxasset://.asphalt-ethanol/sfx/softClick.7e7f3890b37f6ff5bbd1b13ed6645482.ogg",
	},
}
