name: CI

on:
    push:
        branches:
            - main
    pull_request:
    workflow_call:

jobs:
    lint:
        name: CI
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: oven-sh/setup-bun@v2
            - uses: CompeyDev/setup-rokit@v0.1.2
            - run: bun run ci
